health test

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -212,17 +212,10 @@ jobs:
 
           docker inspect spring-\$COLOR --format '{{json .State.Health}}'
 
-          for i in {1..40}; do
-            status=\$(docker inspect -f '{{ .State.Health.Status }}' "spring-\$COLOR" 2>/dev/null || echo starting)
-            echo "loop $i : \$status"
-            [ "$status" = "healthy" ] && break
-            sleep 3
-          done
-
           [ "\$status" = "healthy" ] || {
-           echo 'Health FAIL';
-           docker logs "spring-$COLOR" | tail -50;
-           exit 1;
+            echo 'Health FAIL';
+            docker logs "spring-$COLOR" | tail -50;
+            exit 1;
           }
 
           docker compose -f docker-compose.bluegreen.yml exec nginx nginx -s reload
