deploy edit4

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -101,9 +101,9 @@ jobs:
           done
           
           [ "\$status" = "healthy" ] || { 
-           echo 'Health FAIL' 
-           docker logs "spring-$COLOR" | tail -50 
-           exit 1 
+           echo 'Health FAIL';
+           docker logs "spring-$COLOR" | tail -50;
+           exit 1;
           }
           EOF
 #
